function gridTitle(fig, plot_title)
title_ax = axes(fig, 'Position', [0, 0.98, 1, 0.5]);
set(title_ax, 'Color', 'None', 'XColor', 'None', 'YColor', 'None', ...
    'XTickLabel', {}, 'YTickLabel', {}, 'GridColor', 'None');
text(0.5, 0, plot_title, 'FontSize', 12', 'FontWeight', 'Bold', ...
      'HorizontalAlignment', 'Center', 'VerticalAlignment', 'Middle', ...
      'Interpreter', 'none');
end